# Generated by Django 5.2.8 on 2025-11-30 14:23

import django.db.models.deletion
import myinspectra.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CXRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('abnormality', 'Abnormality'), ('tuberculosis', 'Tuberculosis'), ('pneumothorax', 'Pneumothorax'), ('lung_segmentation', 'Lung Segmentation'), ('pleural_effusion_segmentation', 'Pleural Effusion Segmentation'), ('pneumothorax_segmentation', 'Pneumothorax Segmentation')], default='abnormality', max_length=50)),
                ('api_url', models.URLField(default='http://0.0.0.0:50000/predict', help_text='Full API URL e.g., http://0.0.0.0:50000/predict')),
                ('description', models.TextField(blank=True)),
                ('model_file_path', models.CharField(blank=True, help_text='Path to model weights', max_length=500)),
                ('confidence_stat_file_path', models.CharField(blank=True, help_text='Path to confidence statistics', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'version', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_upload', models.BooleanField(default=False, help_text='Indicates whether the image was uploaded successfully')),
                ('success_process', models.BooleanField(default=False, help_text='Indicates whether the image was predicted successfully')),
                ('success_response', models.BooleanField(default=False, help_text='Indicates whether the response was received successfully')),
                ('model_version', models.ForeignKey(blank=True, help_text='Legacy field', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myinspectra.cxrmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='Disease name from API response', max_length=100)),
                ('model_version', models.CharField(default='v3.5.1', max_length=20)),
                ('prediction_value', models.FloatField(help_text='Raw prediction value from API')),
                ('balanced_score', models.FloatField(help_text='Balanced score from API')),
                ('thresholded_percentage', models.CharField(help_text="Thresholded percentage (e.g., '80%')", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='myinspectra.caserequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('case_request', 'disease_name', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_image', models.ImageField(upload_to=myinspectra.models.heatmap_upload_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap', to='myinspectra.prediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cxr_models', models.ManyToManyField(related_name='profiles', to='myinspectra.cxrmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(editable=False, upload_to=myinspectra.models.raw_image_upload_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myinspectra.caserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(default='v3.5.1', max_length=20)),
                ('segment_image', models.ImageField(upload_to=myinspectra.models.segment_upload_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='myinspectra.caserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverlayHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v3.5.1', max_length=20)),
                ('overlay_image', models.ImageField(upload_to=myinspectra.models.overlay_heatmap_upload_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_heatmaps', to='myinspectra.caserequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('case_request', 'version')},
            },
        ),
    ]
