# Generated by Django 6.0 on 2025-12-15 09:30

import django.db.models.deletion
import myinspectra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinspectra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myinspectra.models.dicom_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='myinspectra.caserequest')),
            ],
        ),
    ]
