# Generated by Django 5.2.8 on 2025-11-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myinspectra", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cxrmodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cxrmodel",
            name="api_url",
            field=models.URLField(
                default="http://0.0.0.0:50000/predict",
                help_text="Full API URL e.g., http://0.0.0.0:50000/predict",
            ),
        ),
        migrations.AddField(
            model_name="cxrmodel",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("abnormality", "Abnormality"),
                    ("tuberculosis", "Tuberculosis"),
                    ("pneumothorax", "Pneumothorax"),
                    ("lung_segmentation", "Lung Segmentation"),
                    ("pleural_effusion_segmentation", "Pleural Effusion Segmentation"),
                    ("pneumothorax_segmentation", "Pneumothorax Segmentation"),
                ],
                default="abnormality",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="caserequest",
            name="model_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy field, use profile instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myinspectra.cxrmodel",
            ),
        ),
        migrations.AlterField(
            model_name="cxrmodel",
            name="confidence_stat_file_path",
            field=models.CharField(
                blank=True, help_text="Path to confidence statistics", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="cxrmodel",
            name="model_file_path",
            field=models.CharField(
                blank=True, help_text="Path to model weights", max_length=500
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cxrmodel",
            unique_together={("name", "version", "service_type")},
        ),
        migrations.CreateModel(
            name="PredictionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cxr_models",
                    models.ManyToManyField(
                        related_name="profiles", to="myinspectra.cxrmodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caserequest",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myinspectra.predictionprofile",
            ),
        ),
    ]
